Fix horse stats being re-rolled on login
CivMC/Civ pull request #334
Opened 2024-02-27 03:12 UTC by MrJeremyFisher

Fixes logging out then back in rerolling horse stats on both untamed and tamed horses.

2024-02-27 15:42 UTC, okx-code reviewed
Would using [CreatureSpawnEvent.SpawnReason.SPAWNER_EGG](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/entity/CreatureSpawnEvent.SpawnReason.html#SPAWNER_EGG) and [CreatureSpawnEvent.SpawnReason.NATURAL](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/entity/CreatureSpawnEvent.SpawnReason.html#NATURAL) work instead?

2024-02-27 15:44 UTC, AngrySoundTech requested changes

2024-02-27 15:44 UTC, AngrySoundTech commented on plugins/simpleadminhacks-paper/src/main/java/com/programmerdan/minecraft/simpleadminhacks/hacks/basic/FasterHorses.java
> +		System.out.println("evt");
Debug print

2024-02-27 15:51 UTC, MrJeremyFisher commented
The Natural spawn reason is called when the server loads an entity and when an entity is spawned, so no.

2024-02-27 15:53 UTC, okx-code commented
ok, what about [getTicksLived](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/Entity.html#getTicksLived())?

2024-02-27 16:53 UTC, MrJeremyFisher commented
Because the horse is spawned every time the riding player logs out and back in, its age at that instant is 0. At least that's what I saw when I tried that as an option

2024-02-27 19:03 UTC, okx-code commented on plugins/simpleadminhacks-paper/src/main/java/com/programmerdan/minecraft/simpleadminhacks/hacks/basic/FasterHorses.java
> +		}
This is not necessary and can be removed

2024-02-27 19:09 UTC, okx-code approved these changes

2024-03-05 18:11 UTC, RedDevel2 approved these changes

2024-03-05 18:13 UTC, merged