Reset warmup on reinforcement update
CivMC/Civ pull request #578
Opened 2024-07-27 03:39 UTC by MrJeremyFisher

Prevents being able to infinitely repair a bastion by patching the associated reinforcement. Also prevents switching groups and materials without a warmup.

2024-10-15 18:47 UTC, okx-code submitted a review, later dismissed
Should include a call to `Bastion.getBastionStorage().updated()`

2024-11-24 20:39 UTC, AngrySoundTech requested changes
oops

2025-02-21 04:37 UTC, okx-code commented on plugins/bastion-paper/src/main/java/isaac/bastion/BastionBlock.java
> +        this.placed = placed;
updated() call should be in here

2025-04-04 23:23 UTC, okx-code approved these changes

2025-04-04 23:23 UTC, merged